import pytest
import json
from pathlib import Path
from score2gp.pdf import extract_tab
from score2gp.build_ir import build_ir_from_tabraw_only
def test_integration_pdf_structural_signaling(tmp_path: Path):
    pdf_path = Path(__file__).parent / "fixtures" / "pdf" / "npg_04d_structural.pdf"
    # 1. Run the extraction (Transport Phase)
    out_dir = tmp_path / "out"
    raw = extract_tab(pdf_path, out_dir)
    # Assert structural signals made it into the raw payload
    signals = raw.get("structural_signals", {})
    sections = signals.get("sections", [])
    repeats = signals.get("repeats", [])
    assert any(s["text"] == "Chorus" for s in sections), "Expected 'Chorus' section to be extracted"
    assert any(r["direction"] == "start" and r["x0"] < 300 for r in repeats), "Expected start repeat to be extracted"
    # Negative control: Unknown bold should not be a section
    assert not any(s["text"] == "UnknownBold" for s in sections), "Unknown bold text should not be extracted as a section"
    # Negative control: Cross-staff isolation
    # Inject a fake section on a different staff index to ensure it doesn't attach
    raw["structural_signals"]["sections"].append({
        "page_index": 1,
        "system_index": 1,
        "staff_index": 99,
        "x0": 250.0,
        "y0": 0.0,
        "x1": 160.0,
        "y1": 10.0,
        "text": "CrossStaffLeak",
        "is_bold": True
    })
    # 2. Run the IR Builder (Consumer Phase)
    raw_path = out_dir / "raw.json"
    with open(raw_path, "w") as f:
        json.dump(raw, f)
    score_ir, diags = build_ir_from_tabraw_only(raw_path)
    # Assert they mapped to the bars correctly
    # The fixture has one bar generated by the fret '0'
    assert len(score_ir.bars) == 1
    bar = score_ir.bars[0]
    assert bar.marker == "Chorus", "The Chorus marker should be attached to the bar (and CrossStaffLeak should be ignored)"
    assert bar.barline == "repeat-end", "The repeat should be attached to the bar"
