from __future__ import annotations

import json
from pathlib import Path
from typer.testing import CliRunner
import pytest

from score2gp.cli import app, _convert_exit_code_for_error
from score2gp.build_ir import BuildIrInputRiskError

# Paths
TINY_PDF = Path("tests/fixtures/pdf/generated_tiny_tab.pdf")
TINY_MUSICXML = Path("tests/fixtures/musicxml/generated_tiny_tab.musicxml")

OVERFULL_MUSICXML = Path("tests/fixtures/musicxml/audiveris_like_overfull_bar.musicxml")
UNSTRUCTURED_PDF = Path("tests/fixtures/pdf/generated_unstructured_tab_text.pdf")


import re

def clean_ansi(text: str) -> str:
    ansi_escape = re.compile(r'\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])')
    return ansi_escape.sub('', text)


def test_cli_help() -> None:
    # 1. CLI help includes convert
    result = CliRunner().invoke(app, ["--help"])
    assert result.exit_code == 0
    assert "convert" in clean_ansi(result.output)

    # 2. convert --help includes all required options
    result = CliRunner().invoke(app, ["convert", "--help"])
    assert result.exit_code == 0
    output = clean_ansi(result.output)
    assert "--pdf" in output
    assert "--musicxml" in output
    assert "--out" in output
    assert "--work-dir" in output
    assert "--json-report" in output
    assert "--strict" in output


def test_cli_convert_missing_pdf(tmp_path) -> None:
    # 3. Missing PDF path exits 1
    workdir = tmp_path / "workdir"
    out_gp = tmp_path / "output.gp"
    non_existent_pdf = tmp_path / "non_existent.pdf"

    result = CliRunner().invoke(
        app,
        [
            "convert",
            "--pdf",
            str(non_existent_pdf),
            "--musicxml",
            str(TINY_MUSICXML),
            "--out",
            str(out_gp),
            "--work-dir",
            str(workdir),
        ],
    )
    assert result.exit_code == 1
    assert "Input PDF file not found" in result.stderr


def test_cli_convert_missing_musicxml(tmp_path) -> None:
    # 4. Missing MusicXML path exits 1
    workdir = tmp_path / "workdir"
    out_gp = tmp_path / "output.gp"

    result = CliRunner().invoke(
        app,
        [
            "convert",
            "--pdf",
            str(TINY_PDF),
            "--out",
            str(out_gp),
            "--work-dir",
            str(workdir),
        ],
    )
    assert result.exit_code == 1
    assert "No timeline previews generated by whole_note_recogniser" in result.stderr


def test_cli_convert_layout_refusal(tmp_path) -> None:
    # 5. Known PDF layout/grouping refusal exits 2 (using unstructured PDF)
    workdir = tmp_path / "workdir"
    out_gp = tmp_path / "output.gp"
    json_report = tmp_path / "report.json"

    result = CliRunner().invoke(
        app,
        [
            "convert",
            "--pdf",
            str(UNSTRUCTURED_PDF),
            "--musicxml",
            str(TINY_MUSICXML),
            "--out",
            str(out_gp),
            "--work-dir",
            str(workdir),
            "--json-report",
            str(json_report),
            "--strict",
        ],
    )
    assert result.exit_code == 2, result.output
    assert not out_gp.exists()

    # 10. Failure path writes JSON report but does not write GP
    assert json_report.exists()
    report = json.loads(json_report.read_text(encoding="utf-8"))
    assert report["status"] == "refused"
    assert report["exit_code"] == 2
    assert report["refusal_code"] is not None


def test_cli_convert_timing_refusal(tmp_path) -> None:
    # 6. Known MusicXML timing/preflight refusal exits 3
    workdir = tmp_path / "workdir"
    out_gp = tmp_path / "output.gp"
    json_report = tmp_path / "report.json"

    result = CliRunner().invoke(
        app,
        [
            "convert",
            "--pdf",
            str(TINY_PDF),
            "--musicxml",
            str(OVERFULL_MUSICXML),
            "--out",
            str(out_gp),
            "--work-dir",
            str(workdir),
            "--json-report",
            str(json_report),
            "--strict",
        ],
    )
    assert result.exit_code == 3, result.output
    assert not out_gp.exists()

    assert json_report.exists()
    report = json.loads(json_report.read_text(encoding="utf-8"))
    assert report["status"] == "refused"
    assert report["exit_code"] == 3
    assert "timing" in report["refusal_code"] or "timing" in report["stage"]


def test_cli_convert_success(tmp_path) -> None:
    # 9. Success path writes output GP and JSON report
    workdir = tmp_path / "workdir"
    out_gp = tmp_path / "output.gp"
    json_report = tmp_path / "report.json"

    result = CliRunner().invoke(
        app,
        [
            "convert",
            "--pdf",
            str(TINY_PDF),
            "--musicxml",
            str(TINY_MUSICXML),
            "--out",
            str(out_gp),
            "--work-dir",
            str(workdir),
            "--json-report",
            str(json_report),
        ],
    )
    assert result.exit_code == 0, result.output
    assert out_gp.exists()
    assert json_report.exists()

    report = json.loads(json_report.read_text(encoding="utf-8"))
    assert report["status"] == "success"
    assert report["exit_code"] == 0
    assert report["output_written"] is True
    assert report["strict"] is True
    assert "diagnostics_paths" in report
    assert report["summary_counts"]["bar_count"] > 0


def test_cli_convert_no_strict_failure(tmp_path) -> None:
    # Test that --no-strict still exits non-zero when no GP output is produced
    workdir = tmp_path / "workdir"
    out_gp = tmp_path / "output.gp"
    json_report = tmp_path / "report.json"

    result = CliRunner().invoke(
        app,
        [
            "convert",
            "--pdf",
            str(UNSTRUCTURED_PDF),
            "--musicxml",
            str(TINY_MUSICXML),
            "--out",
            str(out_gp),
            "--work-dir",
            str(workdir),
            "--json-report",
            str(json_report),
            "--no-strict",
        ],
    )
    assert result.exit_code != 0
    assert not out_gp.exists()

    report = json.loads(json_report.read_text(encoding="utf-8"))
    assert report["status"] == "refused"
    assert report["output_written"] is False
    assert report["strict"] is False


def test_cli_convert_preexisting_out_protection(tmp_path) -> None:
    # Test that a pre-existing output file is not deleted when conversion fails
    workdir = tmp_path / "workdir"
    out_gp = tmp_path / "preexisting.gp"
    out_gp.write_text("pre-existing user content", encoding="utf-8")

    result = CliRunner().invoke(
        app,
        [
            "convert",
            "--pdf",
            str(UNSTRUCTURED_PDF),
            "--musicxml",
            str(TINY_MUSICXML),
            "--out",
            str(out_gp),
            "--work-dir",
            str(workdir),
        ],
    )
    assert result.exit_code != 0
    assert out_gp.exists()
    assert out_gp.read_text(encoding="utf-8") == "pre-existing user content"


def test_cli_convert_json_report_contract(tmp_path) -> None:
    # Assert JSON report contract fields on failure/refusal
    workdir = tmp_path / "workdir"
    out_gp = tmp_path / "output.gp"
    json_report = tmp_path / "report.json"

    result = CliRunner().invoke(
        app,
        [
            "convert",
            "--pdf",
            str(UNSTRUCTURED_PDF),
            "--musicxml",
            str(TINY_MUSICXML),
            "--out",
            str(out_gp),
            "--work-dir",
            str(workdir),
            "--json-report",
            str(json_report),
        ],
    )
    assert result.exit_code != 0
    assert json_report.exists()

    report = json.loads(json_report.read_text(encoding="utf-8"))
    required_keys = {
        "status",
        "stage",
        "exit_code",
        "error_type",
        "refusal_code",
        "recommended_action",
        "output_path",
        "output_written",
        "work_dir",
        "diagnostics_paths",
        "strict",
    }
    for key in required_keys:
        assert key in report


def test_exit_code_mapping_helpers() -> None:
    # Test unit-level exit code mapping helper directly
    e1 = BuildIrInputRiskError(category="pdf_input_class_scanned_pdf_unsupported", stage="layout-gating", message="Scanned PDF")
    assert _convert_exit_code_for_error(e1) == 2

    e2 = BuildIrInputRiskError(category="missing_pdf_grouping", stage="layout-gating", message="Grouping missing")
    assert _convert_exit_code_for_error(e2) == 2

    e3 = BuildIrInputRiskError(category="musicxml_timing_risk", stage="musicxml-import", message="Timing risk")
    assert _convert_exit_code_for_error(e3) == 3

    e4 = BuildIrInputRiskError(category="ascii_alignment_status_unavailable", stage="ascii-scoreir-gate", message="ASCII gate")
    assert _convert_exit_code_for_error(e4) == 4

    e_ascii_pdf_class = BuildIrInputRiskError(
        category="pdf_input_class_ascii_tab_requires_alignment",
        stage="layout-gating",
        message="ASCII tab requires alignment",
    )
    assert _convert_exit_code_for_error(e_ascii_pdf_class) == 4

    e_other = ValueError("Some other error")
    assert _convert_exit_code_for_error(e_other) == 1


def test_existing_subcommands_still_work() -> None:
    # 11. Existing CLI subcommands still work (e.g. export-schema or validate)
    result = CliRunner().invoke(app, ["export-schema", "--help"])
    assert result.exit_code == 0
    assert "--out" in clean_ansi(result.output)


def test_cli_convert_hash_refusal_contains_specific_remediation_hint(tmp_path) -> None:
    from unittest.mock import patch
    from score2gp.ascii_alignment import align_ascii_musicxml_files
    from tests.test_ascii_scoreir_gate import ASCII_GATE_PDF, ASCII_GATE_MUSICXML

    original_align = align_ascii_musicxml_files

    def mock_align(*args, **kwargs):
        alignment = original_align(*args, **kwargs)
        # Mutate to force a stale hash mismatch refusal (using a 64-character mismatching hash)
        alignment.source_pdf_hash = "a" * 64
        if "out_dir" in kwargs and kwargs["out_dir"]:
            out_path = Path(kwargs["out_dir"]) / "ascii_musicxml_alignment.json"
            alignment.to_json_file(out_path)
        return alignment

    workdir = tmp_path / "workdir"
    out_gp = tmp_path / "output.gp"
    json_report = tmp_path / "report.json"

    with patch("score2gp.cli.align_ascii_musicxml_files", side_effect=mock_align):
        result = CliRunner().invoke(
            app,
            [
                "convert",
                "--pdf",
                str(ASCII_GATE_PDF),
                "--musicxml",
                str(ASCII_GATE_MUSICXML),
                "--out",
                str(out_gp),
                "--work-dir",
                str(workdir),
                "--json-report",
                str(json_report),
                "--strict",
            ],
        )

    assert result.exit_code == 4
    assert not out_gp.exists()

    # Verify specific remediation hint in stderr
    assert "re-align the source PDF and MusicXML files to update the stale hashes" in result.stderr
    assert "Check the intermediate diagnostics report for details." not in result.stderr

    # Verify JSON report contains recommended_action
    assert json_report.exists()
    report = json.loads(json_report.read_text(encoding="utf-8"))
    assert report["status"] == "refused"
    assert report["exit_code"] == 4
    assert report["refusal_code"] == "ascii_alignment_stale_sidecar_hash"
    assert report["recommended_action"] == "re-align the source PDF and MusicXML files to update the stale hashes"


def test_cli_convert_hash_refusal_does_not_print_full_hashes_in_remediation(tmp_path) -> None:
    from unittest.mock import patch
    from score2gp.ascii_alignment import align_ascii_musicxml_files
    from tests.test_ascii_scoreir_gate import ASCII_GATE_PDF, ASCII_GATE_MUSICXML

    original_align = align_ascii_musicxml_files

    def mock_align(*args, **kwargs):
        alignment = original_align(*args, **kwargs)
        # Mutate to force a stale hash mismatch refusal on both PDF and MusicXML (using 64-character hashes)
        alignment.source_pdf_hash = "a" * 64
        alignment.source_musicxml_hash = "b" * 64
        if "out_dir" in kwargs and kwargs["out_dir"]:
            out_path = Path(kwargs["out_dir"]) / "ascii_musicxml_alignment.json"
            alignment.to_json_file(out_path)
        return alignment

    workdir = tmp_path / "workdir"
    out_gp = tmp_path / "output.gp"
    json_report = tmp_path / "report.json"

    with patch("score2gp.cli.align_ascii_musicxml_files", side_effect=mock_align):
        result = CliRunner().invoke(
            app,
            [
                "convert",
                "--pdf",
                str(ASCII_GATE_PDF),
                "--musicxml",
                str(ASCII_GATE_MUSICXML),
                "--out",
                str(out_gp),
                "--work-dir",
                str(workdir),
                "--json-report",
                str(json_report),
                "--strict",
            ],
        )

    assert result.exit_code == 4
    assert not out_gp.exists()

    assert "re-align the source PDF and MusicXML files to update the stale hashes" in result.stderr
    assert "a" * 64 not in result.stderr
    assert "b" * 64 not in result.stderr

    assert json_report.exists()
    report = json.loads(json_report.read_text(encoding="utf-8"))
    assert report["refusal_code"] == "ascii_alignment_stale_sidecar_hash"
    assert report["recommended_action"] == "re-align the source PDF and MusicXML files to update the stale hashes"

def _read_score_gpif(gp_path) -> str:
    import zipfile
    with zipfile.ZipFile(gp_path) as package:
        return package.read("Content/score.gpif").decode("utf-8")

def test_cli_convert_editable_draft_success(tmp_path) -> None:
    workdir = tmp_path / "workdir"
    out_gp = tmp_path / "output.gp"
    json_report = tmp_path / "report.json"

    result = CliRunner().invoke(
        app,
        [
            "convert",
            "--pdf",
            str(TINY_PDF),
            "--editable-draft",
            "--out",
            str(out_gp),
            "--work-dir",
            str(workdir),
            "--json-report",
            str(json_report),
        ],
    )
    assert result.exit_code == 0, result.output
    assert out_gp.exists()
    assert json_report.exists()
    import json
    report = json.loads(json_report.read_text(encoding="utf-8"))
    assert report.get("pdf_only_diagnostics", {}).get("inferred_rhythm_status") == "defaulted_placeholder"


    gpif_content = _read_score_gpif(out_gp)
    assert "Editable draft generated from PDF tablature" in gpif_content
    assert "Rhythms defaulted to quarter notes" in gpif_content
    assert "timing was not recognised" in gpif_content
    assert "Tuning defaulted to E Standard" in gpif_content
    assert "Time signature defaulted to 4/4" in gpif_content
    assert "Tempo defaulted to 120 bpm" in gpif_content
    assert "Standard notation and notation/tab alignment were skipped" in gpif_content
    assert "Rests/silence may be omitted" in gpif_content

def test_cli_convert_editable_draft_dense_bar(tmp_path) -> None:
    # Use a synthetic dense bar mock in TabRaw
    from score2gp.tabraw import TabRaw, TabCandidate
    from score2gp.ir import BoundingBox
    import json

    tabraw = TabRaw(
        candidates=[
            TabCandidate(
                id=f"c-{i}",
                kind="fret",
                raw_text="0",
                parsed_fret=0,
                x=10.0 + i * 5.0,
                y=10.0,
                string=1,
                bar_index=1,
                system_index=1,
                staff_index=1,
                page_index=1,
                bbox=BoundingBox(page=1, x0=10.0 + i * 5.0, y0=10.0, x1=15.0 + i * 5.0, y1=15.0)
            ) for i in range(20) # 20 events in 1 bar
        ]
    )

    workdir = tmp_path / "workdir"
    out_gp = tmp_path / "output.gp"
    from unittest.mock import patch
    with patch("score2gp.cli.extract_tab_file", side_effect=lambda *args, **kwargs: {"candidates_count": 20}):
        with patch("score2gp.cli.inspect_pdf_file", side_effect=lambda *args, **kwargs: {}):
            with patch("score2gp.build_ir.TabRaw.from_json_file", return_value=tabraw):
                result = CliRunner().invoke(
                    app,
                    [
                        "convert",
                        "--pdf",
                        str(TINY_PDF),
                        "--editable-draft",
                        "--out",
                        str(out_gp),
                        "--work-dir",
                        str(workdir),
                    ],
                )
                assert result.exit_code == 0, result.output
                assert out_gp.exists()

                import re
                gpif_content = _read_score_gpif(out_gp)
                notes_count = len(re.findall(r'<Note\b', gpif_content))
                assert notes_count >= 20, f"Expected at least 20 notes, found {notes_count}"

def test_cli_convert_lesson_3_quality_gate(tmp_path: Path) -> None:
    pdf_path = Path("../score2gp-private-fixtures/fixtures/private/Lesson-3.pdf")
    ref_path = Path("../score2gp-private-fixtures/fixtures/private/Lesson-3.gp")
    if not pdf_path.exists() or not ref_path.exists():
        pytest.skip("Private fixture Lesson-3 not found")

    out_gp = tmp_path / "Lesson-3.gp"
    work_dir = tmp_path / "work"
    json_report = tmp_path / "report.json"

    result = CliRunner().invoke(app, [
        "convert",
        "--pdf", str(pdf_path),
        "--ref-gp", str(ref_path),
        "--require-ref-match",
        "--out", str(out_gp),
        "--work-dir", str(work_dir),
        "--json-report", str(json_report),
    ], catch_exceptions=False)

    if result.exit_code != 0:
        print("CLI output:", result.output)
        print("CLI error:", result.stderr)
    assert result.exit_code == 0

    assert json_report.exists()
    report = json.loads(json_report.read_text(encoding="utf-8"))
    assert report["status"] == "success"
    assert report["stage"] == "gp-write"
    assert report["output_written"] is True
    assert report["summary_counts"]["bar_count"] == 66
    assert report["summary_counts"]["empty_bar_count"] == 0
    assert report["summary_counts"]["semantic_differences"] == {}

    # Verify no zero-note musical events and plausible scalar/arpeggio shapes
    shapes = report["summary_counts"]["per_bar_event_shapes"]
    for i in range(12):
        if not shapes[i]:
            continue
        assert 0 not in shapes[i], f"Zero-note event emitted in bar {i+1}"
        assert max(shapes[i]) <= 3, f"Four-note chord event in scalar bar {i+1}"
        # Plausible shape: mostly single notes (at least half are single notes)
        assert shapes[i].count(1) >= len(shapes[i]) // 2, f"Not a plausible scalar shape in bar {i+1}"

    # A diagnostic artifact is still produced; it must not be mistaken for a passing transcription.

    # A diagnostic artifact is still produced; it must not be mistaken for a passing transcription.
    assert out_gp.exists()
    gpif_content = _read_score_gpif(out_gp)
    notes_count = len(re.findall(r'<Note\b', gpif_content))
    assert notes_count > 150, f"Expected pitch fallback to avoid an empty tail, found {notes_count} notes"

    # Assert deterministic musicxml used strict 4/4 and has no fake tie restoration
    musicxml_path = work_dir / "deterministic_omr.musicxml"
    assert musicxml_path.exists()

    import xml.etree.ElementTree as ET

    assert len(ET.parse(musicxml_path).getroot().findall(".//measure")) == 66
    xml_content = musicxml_path.read_text(encoding="utf-8")
    assert "<beats>4</beats>" in xml_content
    assert "<tie " not in xml_content
    assert "<tied " not in xml_content
