"""DUR-01: every note and rest carries its own duration, read from its note type and grouping.

The fixtures under tests/fixtures/pdf/dur_01/ are generated by scripts/dur_01_make_fixtures.py in
the vector vocabulary of the corpus. Expectations here are written by hand from the engraved
music, not derived from the generator. Spacing in every fixture is uniform, so it carries no rhythm.
"""

from __future__ import annotations

import json
import math
from fractions import Fraction
from pathlib import Path

import pytest
from typer.testing import CliRunner

from score2gp.cli import app
from score2gp.notation_omr import note_duration as nd
from score2gp.notation_omr.note_duration import read_note_durations

FIXTURES = Path(__file__).parent / "fixtures" / "pdf" / "dur_01"
VALUES = {"whole": Fraction(4), "half": Fraction(2), "quarter": Fraction(1), "eighth": Fraction(1, 2),
          "16th": Fraction(1, 4), "32nd": Fraction(1, 8), "64th": Fraction(1, 16)}

N, R = "note", "rest"
EXPECTED = {
    # The maintainer's example: one bar mixing a half note and eight thirty-second notes (3/4).
    "half_and_32nds": [[(N, "half", 0, None)] + [(N, "32nd", 0, None)] * 8],
    "dotted": [
        [(N, "half", 1, None), (N, "quarter", 0, None)],
        [(N, "half", 2, None), (N, "eighth", 0, None)],
        [(N, "quarter", 2, None), (N, "16th", 0, None), (N, "quarter", 1, None), (N, "eighth", 0, None)],
    ],
    "mixed_beams": [[
        (N, "eighth", 0, None), (N, "16th", 0, None), (N, "16th", 0, None),
        (N, "eighth", 1, None), (N, "16th", 0, None),
        (N, "16th", 0, None), (N, "eighth", 1, None),
        (N, "16th", 0, None), (N, "16th", 0, None), (N, "16th", 0, None), (N, "16th", 0, None),
    ]],
    "triplet": [[
        (N, "eighth", 0, (3, 2)), (N, "eighth", 0, (3, 2)), (N, "eighth", 0, (3, 2)),
        (N, "quarter", 0, (3, 2)), (N, "quarter", 0, (3, 2)), (N, "quarter", 0, (3, 2)),
        (N, "quarter", 0, None),
    ]],
    "rests": [
        [(R, "whole", 0, None)],
        [(R, "half", 0, None), (R, "quarter", 0, None), (R, "eighth", 0, None), (R, "16th", 0, None),
         (R, "32nd", 0, None), (R, "64th", 0, None), (N, "64th", 0, None)],
    ],
    "tie_across_barline": [
        [(N, "half", 0, None), (N, "quarter", 0, None), (N, "quarter", 0, None)],
        [(N, "quarter", 0, None), (N, "half", 1, None)],
    ],
}
TIME_SIGNATURES = {"half_and_32nds": (3, 4)}


def _sounding(written: str, dots: int, tuplet: tuple[int, int] | None) -> Fraction:
    value = VALUES[written] * (2 - Fraction(1, 2 ** dots))
    return value * Fraction(tuplet[1], tuplet[0]) if tuplet else value


def _bars(result: dict) -> list[list[dict]]:
    bars: dict[int, list[dict]] = {}
    for event in result["events"]:
        bars.setdefault(event["bar_index"], []).append(event)
    return [sorted(bars[i], key=lambda e: e["event_index"]) for i in sorted(bars)]


def _summary(event: dict) -> tuple:
    tuplet = event.get("tuplet")
    return (event["kind"] if event["kind"] == R else N, event["written"], event["dots"]["count"],
            (tuplet["actual"], tuplet["normal"]) if tuplet else None)


def _mismatches(name: str) -> list[str]:
    result = read_note_durations(FIXTURES / f"{name}.pdf")
    bars = _bars(result)
    problems = []
    if len(bars) != len(EXPECTED[name]):
        return [f"{name}: {len(bars)} bars read, {len(EXPECTED[name])} expected"]
    for b, (got, want) in enumerate(zip(bars, EXPECTED[name])):
        if len(got) != len(want):
            problems.append(f"{name} bar {b}: {len(got)} events, {len(want)} expected")
            continue
        for e, (event, expected) in enumerate(zip(got, want)):
            if event["status"] != "read":
                problems.append(f"{name} bar {b} event {e}: unread ({event['reason']})")
            elif _summary(event) != expected:
                problems.append(f"{name} bar {b} event {e}: {_summary(event)} != {expected}")
            elif Fraction(event["duration_quarters"]) != _sounding(expected[1], expected[2], expected[3]):
                problems.append(f"{name} bar {b} event {e}: duration {event['duration_quarters']}")
    return problems


@pytest.mark.parametrize("name", sorted(EXPECTED))
def test_synthetic_fixture_reads_every_event_correctly(name):
    assert _mismatches(name) == []


@pytest.mark.parametrize("name", sorted(EXPECTED))
def test_bar_total_is_a_check_that_agrees_with_the_time_signature(name):
    result = read_note_durations(FIXTURES / f"{name}.pdf")
    numerator, denominator = TIME_SIGNATURES.get(name, (4, 4))
    assert result["bar_checks"], "every bar reports a check"
    for check in result["bar_checks"]:
        assert check["time_signature"] == f"{numerator}/{denominator}"
        assert check["time_signature_source"] == "text_glyphs"
        assert check["status"] == "match", check
        assert Fraction(check["total_quarters"]) == Fraction(4 * numerator, denominator)


def test_every_field_cites_its_source_symbols():
    for name in EXPECTED:
        for event in read_note_durations(FIXTURES / f"{name}.pdf")["events"]:
            assert event["status"] == "read"
            if event["kind"] == R:
                assert event["rest"]["glyph"] == event["written"] and event["rest"]["source"]
                assert event["notehead"] is None and event["stem"] is None
            else:
                assert event["notehead"]["sources"], event
                assert event["notehead"]["kind"] in ("filled", "hollow")
                if event["written"] != "whole":
                    assert event["stem"]["source"]
                for glyph in event["flags"]["glyphs"]:
                    assert glyph["source"] and glyph["hooks"] >= 1
                assert len(event["beams"]["sources"]) == event["beams"]["count"] or event["beams"]["count"] == 0
            assert len(event["dots"]["sources"]) == event["dots"]["count"]
            if event["tuplet"]:
                assert event["tuplet"]["sources"]


def test_flag_counts_are_identified_flag_glyphs_not_drawings_or_segments():
    result = read_note_durations(FIXTURES / "dotted.pdf")
    bars = _bars(result)
    eighth = bars[1][1]  # a single flag blade drawn with dozens of straight segments
    assert eighth["flags"]["count"] == 1 and len(eighth["flags"]["glyphs"]) == 1
    sixteenth = bars[2][1]  # two blades drawn as two separate drawings
    assert sixteenth["flags"]["count"] == 2 and len(sixteenth["flags"]["glyphs"]) == 2
    rests = _bars(read_note_durations(FIXTURES / "rests.pdf"))
    sixty_fourth = rests[1][6]  # four blades drawn as one glyph path
    assert sixty_fourth["flags"]["count"] == 4 and len(sixty_fourth["flags"]["glyphs"]) == 1
    assert sixty_fourth["flags"]["glyphs"][0]["hooks"] == 4


def test_beam_count_is_the_number_of_distinct_beam_lines_at_each_stem():
    bars = _bars(read_note_durations(FIXTURES / "mixed_beams.pdf"))
    assert [e["beams"]["count"] for e in bars[0]] == [1, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2]
    groups = [e["beams"]["group"] for e in bars[0]]
    assert len({groups[0], groups[3], groups[5], groups[7]}) == 4
    assert groups[0] == groups[1] == groups[2]


def test_ties_are_recorded_and_values_are_not_merged():
    bars = _bars(read_note_durations(FIXTURES / "tie_across_barline.pdf"))
    last, first = bars[0][2], bars[1][0]
    assert last["tie"]["start"] and not last["tie"]["stop"]
    assert first["tie"]["stop"] and not first["tie"]["start"]
    assert last["tie"]["sources"] == first["tie"]["sources"]
    assert last["duration_quarters"] == "1" and first["duration_quarters"] == "1"


def test_ambiguous_symbols_are_recorded_unread_with_a_located_reason_never_guessed():
    result = read_note_durations(FIXTURES / "ambiguous.pdf")
    events = _bars(result)[0]
    reasons = [(e["status"], e["reason"]) for e in events]
    assert reasons == [
        ("unread", "filled_notehead_without_stem"),
        ("unread", "flag_and_beam_on_one_stem"),
        ("read", None),
        ("unread", "tuplet_number_unassociated"),
        ("read", None),
    ]
    for event in events:
        if event["status"] == "unread":
            assert event["written"] is None and event["duration_quarters"] is None
            location = event["location"]
            assert {"page_index", "system_index", "bar_index", "event_index", "bbox"} <= set(location)
    check = result["bar_checks"][0]
    assert check["status"] == "incomplete" and check["unread_events"] == 3


def test_bar_total_never_changes_a_duration(monkeypatch):
    """Declaring a different time signature changes the check, never the records."""
    base = read_note_durations(FIXTURES / "half_and_32nds.pdf")
    monkeypatch.setattr(nd, "_read_time_signature", lambda *args, **kwargs: None)
    other = read_note_durations(FIXTURES / "half_and_32nds.pdf", time_signature=(4, 4))
    assert [e["duration_quarters"] for e in other["events"]] == [e["duration_quarters"] for e in base["events"]]
    assert other["bar_checks"][0]["status"] == "mismatch"
    assert other["bar_checks"][0]["time_signature_source"] == "caller_declared"


def test_cli_writes_records_under_the_chosen_directory(tmp_path):
    out = tmp_path / "durations"
    result = CliRunner().invoke(app, ["read-note-durations", "--pdf", str(FIXTURES / "dotted.pdf"), "--out", str(out)])
    assert result.exit_code == 0, result.output
    written = json.loads((out / "note-durations.json").read_text(encoding="utf-8"))
    assert written["schema"] == nd.SCHEMA
    assert len(written["events"]) == 8
    assert written["summary"]["read_events"] == 8 and written["summary"]["unread_events"] == 0


# --- mutation checks: each mutant must make the fixture expectations fail -------------------------

def _failing_fixtures() -> set[str]:
    return {name for name in EXPECTED if _mismatches(name)}


def test_mutation_flag_identification_replaced_by_segment_count(monkeypatch):
    monkeypatch.setattr(nd, "_flag_hooks", lambda glyph, stem, space: len(glyph.drawing["items"]))
    assert {"dotted", "rests"} <= _failing_fixtures()


def test_mutation_dots_ignored(monkeypatch):
    monkeypatch.setattr(nd, "_augmentation_dots", lambda *args, **kwargs: [])
    assert {"dotted", "mixed_beams", "tie_across_barline"} <= _failing_fixtures()


def test_mutation_tuplets_ignored(monkeypatch):
    monkeypatch.setattr(nd, "_read_tuplets", lambda *args, **kwargs: ([], []))
    assert "triplet" in _failing_fixtures()


def test_mutation_values_from_the_number_of_events_in_a_group(monkeypatch):
    real = nd._written_value

    def by_group_size(parts):
        size = parts["beam_group_size"]
        return real(dict(parts, beam_count=max(1, round(math.log2(size))))) if size else real(parts)

    monkeypatch.setattr(nd, "_written_value", by_group_size)
    assert "mixed_beams" in _failing_fixtures()
