import zipfile
import json
import xml.etree.ElementTree as ET
from pathlib import Path
import hashlib

def main():
    repo_root = Path(__file__).resolve().parent.parent.parent
    gp_path = repo_root.parent / "score2gp-private-fixtures" / "fixtures" / "private" / "Lesson-6.gp"
    
    if not gp_path.exists():
        print(f"Skipping: {gp_path} not found")
        return

    with open(gp_path, "rb") as f:
        file_bytes = f.read()
    source_hash = hashlib.sha256(file_bytes).hexdigest()

    with zipfile.ZipFile(gp_path, 'r') as z:
        gpif_bytes = z.read("Content/score.gpif")
    
    root = ET.fromstring(gpif_bytes)
    
    rhythms = {}
    for r in root.findall(".//Rhythms/Rhythm"):
        r_id = r.get("id")
        nv = r.find("NoteValue")
        if r_id is not None and nv is not None:
            rhythms[r_id] = nv.text.lower()
            
    notes = {}
    for n in root.findall(".//Notes/Note"):
        n_id = n.get("id")
        string = None
        fret = None
        props = n.find("Properties")
        if props is not None:
            for p in props.findall("Property"):
                if p.get("name") == "String":
                    s_node = p.find("String") if p.find("String") is not None else p.find("Integer")
                    if s_node is not None:
                        string = 6 - int(s_node.text)  # Map 0-indexed (from Low E) to 1-indexed (from High E)
                elif p.get("name") == "Fret":
                    f_node = p.find("Fret") if p.find("Fret") is not None else p.find("Integer")
                    if f_node is not None:
                        fret = int(f_node.text)
        if n_id is not None:
            notes[n_id] = {"string": string, "fret": fret}
            
    beats = {}
    for b in root.findall(".//Beats/Beat"):
        b_id = b.get("id")
        r_ref = b.find("Rhythm")
        r_id = r_ref.get("ref") if r_ref is not None else None
        n_ids = []
        for nn in b.findall("Notes"):
            if nn.text: n_ids.extend(nn.text.split())
        if b_id is not None:
            beats[b_id] = {"rhythm_id": r_id, "notes": n_ids}
            
    voices = {}
    for v in root.findall(".//Voices/Voice"):
        v_id = v.get("id")
        b_ids = []
        for bn in v.findall("Beats"):
            if bn.text: b_ids.extend(bn.text.split())
        if v_id is not None:
            voices[v_id] = b_ids
            
    bars_list = []
    for m_idx, bar in enumerate(root.findall(".//Bars/Bar")):
        m_voices = []
        for vn in bar.findall("Voices"):
            if vn.text:
                for v_id in vn.text.split():
                    if v_id != "-1": m_voices.append(v_id)
        
        bar_index = m_idx + 1
        for v_id in m_voices:
            for b_id in voices.get(v_id, []):
                beat = beats.get(b_id)
                if not beat: continue
                r_id = beat["rhythm_id"]
                r_val = rhythms.get(r_id)
                dur_name = r_val
                
                # We need to correctly translate 16th which in GP XML is "16th" or "sixteenth"
                if r_val == "sixteenth": dur_name = "16th"
                
                for n_id in beat["notes"]:
                    note = notes.get(n_id)
                    if note and note["fret"] is not None and note["string"] is not None:
                        bars_list.append({
                            "bar_index": bar_index,
                            "string": note["string"],
                            "fret": note["fret"],
                            "duration_name": dur_name
                        })

    cand_3_1_1 = next((b["duration_name"] for b in bars_list if b["bar_index"] == 1 and b["string"] == 1 and b["fret"] == 3), None)
    cand_5_1_1 = next((b["duration_name"] for b in bars_list if b["bar_index"] == 1 and b["string"] == 1 and b["fret"] == 5), None)
    cands_15_1 = next((b["duration_name"] for b in bars_list if b["bar_index"] == 15 and b["string"] == 1 and b["fret"] == 15), None)

    oracle = {
        "_provenance": {
            "source_file": "Lesson-6.gp",
            "source_hash": f"sha256:{source_hash}",
            "derivation": "Generated by tests/fixtures/make_lesson6_oracle.py by directly parsing Content/score.gpif from Guitar Pro 7 archive",
            "independent_reference": "Lesson-6.gp from score2gp-private-fixtures"
        },
        "cand_3_1_1": cand_3_1_1,
        "cand_5_1_1": cand_5_1_1,
        "cands_15_1": cands_15_1
    }

    out_path = Path(__file__).resolve().parent / "lesson6_duration_oracle.json"
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(oracle, f, indent=2)
    print(f"Wrote oracle to {out_path}")
    print(oracle)

if __name__ == "__main__":
    main()
