import xml.etree.ElementTree as ET
from xml.dom import minidom
from pathlib import Path
from .whole_note_recogniser import run_recognition_on_file

def generate_musicxml_sidecar(pdf_path: Path, out_mxl: Path) -> Path:
    res = run_recognition_on_file(
        pdf_path,
        include_x_aligned_clusters=True,
        include_left_margin_candidates=True,
        include_flag_beam_candidates=True,
        include_ledger_line_candidates=True,
    )
    previews = res.get("timeline_preview", [])
    if not previews:
        raise ValueError("No timeline previews generated by whole_note_recogniser.")

    # Flatten measures across all systems
    measures = []
    for preview in previews:
        for m in preview.get("measures", []):
            measures.append(m)

    root = ET.Element("score-partwise", version="3.1")
    part_list = ET.SubElement(root, "part-list")
    score_part = ET.SubElement(part_list, "score-part", id="P1")
    ET.SubElement(score_part, "part-name").text = "Standard Notation"

    part = ET.SubElement(root, "part", id="P1")

    for global_m_idx, m_data in enumerate(measures):
        measure_el = ET.SubElement(part, "measure", number=str(global_m_idx + 1))

        events = m_data.get("events", [])
        events = sorted(events, key=lambda e: e.get("start_tick", 0))

        # Calculate actual measure duration by simulating MusicXML cursor advancement
        total_ticks = 0
        last_start = -1
        last_was_rest = False
        for e in events:
            st = e.get("start_tick", 0)
            is_rest = e.get("symbol_type", "").endswith("rest") or not e.get("resolved_pitch")
            is_chord = (st == last_start and not is_rest and not last_was_rest)
            
            if not is_chord:
                total_ticks += e.get("duration_ticks", 960)
            
            last_start = st
            last_was_rest = is_rest

        if total_ticks == 0:
            total_ticks = 3840  # Default to 4/4 if empty

        import math
        beats = max(4, math.ceil(total_ticks / 960))

        if total_ticks > 0:
            attrs = ET.SubElement(measure_el, "attributes")
            ET.SubElement(attrs, "divisions").text = "960"
            key = ET.SubElement(attrs, "key")
            ET.SubElement(key, "fifths").text = "0"
            time = ET.SubElement(attrs, "time")
            ET.SubElement(time, "beats").text = str(beats)
            ET.SubElement(time, "beat-type").text = "4"
            clef = ET.SubElement(attrs, "clef")
            ET.SubElement(clef, "sign").text = "G"
            ET.SubElement(clef, "line").text = "2"

        events = sorted(events, key=lambda e: e.get("start_tick", 0))

        def write_events(evs):
            last_start_tick = -1
            last_was_rest = False
            for e in evs:
                start_tick = e.get("start_tick", 0)
                note_el = ET.SubElement(measure_el, "note")

                is_rest = e.get("symbol_type", "").endswith("rest")
                pitch_str = e.get("resolved_pitch")
                if not pitch_str:
                    is_rest = True

                if start_tick == last_start_tick and not is_rest and not last_was_rest:
                    ET.SubElement(note_el, "chord")

                if is_rest:
                    ET.SubElement(note_el, "rest")
                else:
                    step = pitch_str[0]
                    octave = pitch_str[-1]
                    pitch_el = ET.SubElement(note_el, "pitch")
                    ET.SubElement(pitch_el, "step").text = step
                    if len(pitch_str) == 3:
                        acc = pitch_str[1]
                        if acc == "#":
                            ET.SubElement(pitch_el, "alter").text = "1"
                        elif acc == "b":
                            ET.SubElement(pitch_el, "alter").text = "-1"
                    ET.SubElement(pitch_el, "octave").text = octave

                dur_ticks = e.get("duration_ticks", 960)
                ET.SubElement(note_el, "duration").text = str(dur_ticks)

                if e.get("is_tie_stop"):
                    ET.SubElement(note_el, "tie", type="stop")
                if e.get("is_tie_start"):
                    ET.SubElement(note_el, "tie", type="start")

                ET.SubElement(note_el, "voice").text = "1"

                type_map = {
                    3840: "whole",
                    1920: "half",
                    1440: "quarter",
                    960: "quarter",
                    720: "eighth",
                    480: "eighth",
                    360: "16th",
                    240: "16th",
                    120: "32nd",
                    60: "64th"
                }
                is_dotted = False
                if dur_ticks in [1440, 720, 360]:
                    is_dotted = True

                note_type = type_map.get(dur_ticks, "quarter")
                ET.SubElement(note_el, "type").text = note_type
                if is_dotted:
                    ET.SubElement(note_el, "dot")

                if e.get("is_tie_start") or e.get("is_tie_stop"):
                    notations_el = ET.SubElement(note_el, "notations")
                    if e.get("is_tie_stop"):
                        ET.SubElement(notations_el, "tied", type="stop")
                    if e.get("is_tie_start"):
                        ET.SubElement(notations_el, "tied", type="start")

                last_start_tick = start_tick
                last_was_rest = is_rest

        write_events(events)

    xml_str = minidom.parseString(ET.tostring(root)).toprettyxml(indent="  ")
    out_mxl.write_text(xml_str, encoding="utf-8")
    return out_mxl
