import xml.etree.ElementTree as ET
from xml.dom import minidom
from pathlib import Path
from .whole_note_recogniser import run_recognition_on_file

def generate_musicxml_sidecar(pdf_path: Path, out_mxl: Path) -> Path:
    res = run_recognition_on_file(
        pdf_path,
        include_x_aligned_clusters=True,
        include_left_margin_candidates=True,
        include_flag_beam_candidates=True,
        include_ledger_line_candidates=True,
        assume_treble_clef=True,
    )
    previews = res.get("timeline_preview", [])
    if not previews:
        raise ValueError("No timeline previews generated by whole_note_recogniser.")

    # Flatten measures across all systems, tracking page and system indices.
    measures = []
    for preview in previews:
        page_idx = preview.get("page_index", 1)
        sys_idx = preview.get("system_index", 1)
        system_measures = preview.get("measures", [])
        same_page_previews = [p for p in previews if p.get("page_index") == page_idx]
        min_sys_idx = min(
            (p.get("system_index", 0) for p in same_page_previews), default=0
        )
        for local_m_idx, m in enumerate(system_measures):
            m_copy = dict(m)
            m_copy["page_index"] = page_idx
            m_copy["system_index"] = sys_idx
            m_copy["is_first_of_system"] = local_m_idx == 0
            m_copy["is_first_system_of_page"] = sys_idx == min_sys_idx
            measures.append(m_copy)

    root = ET.Element("score-partwise", version="3.1")
    part_list = ET.SubElement(root, "part-list")
    score_part = ET.SubElement(part_list, "score-part", id="P1")
    ET.SubElement(score_part, "part-name").text = "Standard Notation"

    part = ET.SubElement(root, "part", id="P1")

    for global_m_idx, m_data in enumerate(measures):
        measure_el = ET.SubElement(part, "measure", number=str(global_m_idx + 1))

        if global_m_idx > 0 and m_data.get("is_first_of_system"):
            print_el = ET.SubElement(measure_el, "print")
            if m_data.get("is_first_system_of_page"):
                print_el.set("new-page", "yes")
            else:
                print_el.set("new-system", "yes")

        section_name = m_data.get("section_name")
        if section_name:
            dir_el = ET.SubElement(measure_el, "direction", placement="above")
            dt_el = ET.SubElement(dir_el, "direction-type")
            ET.SubElement(dt_el, "rehearsal").text = section_name

        tempo_bpm = m_data.get("tempo_bpm")
        if tempo_bpm:
            dir_el = ET.SubElement(measure_el, "direction", placement="above")
            dt_el = ET.SubElement(dir_el, "direction-type")
            met_el = ET.SubElement(dt_el, "metronome")
            ET.SubElement(met_el, "beat-unit").text = "quarter"
            ET.SubElement(met_el, "per-minute").text = str(tempo_bpm)
            ET.SubElement(dir_el, "sound", tempo=str(tempo_bpm))

        if global_m_idx == 0:
            attrs = ET.SubElement(measure_el, "attributes")
            ET.SubElement(attrs, "divisions").text = "960"
            key = ET.SubElement(attrs, "key")
            ET.SubElement(key, "fifths").text = "0"
            time = ET.SubElement(attrs, "time")
            ET.SubElement(time, "beats").text = "4"
            ET.SubElement(time, "beat-type").text = "4"
            clef = ET.SubElement(attrs, "clef")
            ET.SubElement(clef, "sign").text = "G"
            ET.SubElement(clef, "line").text = "2"

        events = m_data.get("events", [])

        # Group events by voice
        voices = {}
        for e in events:
            v = str(e.get("voice", 1))
            if v not in voices:
                voices[v] = []
            voices[v].append(e)

        def write_voice_events(evs, voice_id):
            evs = sorted(evs, key=lambda e: e.get("start_tick", 0))
            last_start_tick = -1
            last_was_rest = False
            total_duration = 0

            for e in evs:
                start_tick = e.get("start_tick", 0)
                note_el = ET.SubElement(measure_el, "note")

                is_rest = e.get("symbol_type", "").endswith("rest")
                pitch_str = e.get("resolved_pitch")
                if not pitch_str:
                    is_rest = True

                if start_tick == last_start_tick and not is_rest and not last_was_rest:
                    ET.SubElement(note_el, "chord")

                if is_rest:
                    ET.SubElement(note_el, "rest")
                else:
                    step = pitch_str[0]
                    octave = pitch_str[-1]
                    pitch_el = ET.SubElement(note_el, "pitch")
                    ET.SubElement(pitch_el, "step").text = step
                    if len(pitch_str) == 3:
                        acc = pitch_str[1]
                        if acc == "#":
                            ET.SubElement(pitch_el, "alter").text = "1"
                        elif acc == "b":
                            ET.SubElement(pitch_el, "alter").text = "-1"
                    ET.SubElement(pitch_el, "octave").text = octave

                dur_ticks = e.get("duration_ticks", 960)
                ET.SubElement(note_el, "duration").text = str(dur_ticks)

                if e.get("is_tie_stop"):
                    ET.SubElement(note_el, "tie", type="stop")
                if e.get("is_tie_start"):
                    ET.SubElement(note_el, "tie", type="start")

                ET.SubElement(note_el, "voice").text = voice_id

                type_map = {
                    3840: "whole",
                    2880: "half",
                    1920: "half",
                    1440: "quarter",
                    960: "quarter",
                    720: "eighth",
                    640: "quarter", # triplet quarter
                    480: "eighth",
                    360: "16th",
                    320: "eighth", # triplet eighth
                    240: "16th",
                    160: "16th", # triplet sixteenth
                    120: "32nd",
                    80: "32nd", # triplet 32nd
                    60: "64th"
                }
                is_dotted = False
                if dur_ticks in [2880, 1440, 720, 360]:
                    is_dotted = True

                note_type = type_map.get(dur_ticks, "quarter")
                ET.SubElement(note_el, "type").text = note_type
                if is_dotted:
                    ET.SubElement(note_el, "dot")

                tuplet_info = {
                    640: (3, 2),
                    320: (3, 2),
                    160: (3, 2),
                    80: (3, 2)
                }
                if dur_ticks in tuplet_info:
                    act, norm = tuplet_info[dur_ticks]
                    tm = ET.SubElement(note_el, "time-modification")
                    ET.SubElement(tm, "actual-notes").text = str(act)
                    ET.SubElement(tm, "normal-notes").text = str(norm)

                if e.get("is_tie_start") or e.get("is_tie_stop"):
                    notations_el = ET.SubElement(note_el, "notations")
                    if e.get("is_tie_stop"):
                        ET.SubElement(notations_el, "tied", type="stop")
                    if e.get("is_tie_start"):
                        ET.SubElement(notations_el, "tied", type="start")

                last_start_tick = start_tick
                last_was_rest = is_rest

                # Add to total duration if it's not a chord note
                if note_el.find("chord") is None:
                    total_duration += dur_ticks

            return total_duration

        sorted_voices = sorted(voices.keys())
        for i, v_id in enumerate(sorted_voices):
            v_dur = write_voice_events(voices[v_id], v_id)
            if i < len(sorted_voices) - 1 and v_dur > 0:
                backup = ET.SubElement(measure_el, "backup")
                ET.SubElement(backup, "duration").text = str(v_dur)

        b_style = m_data.get("barline_style", "simple")
        if b_style in ("double", "final"):
            bar_el = ET.SubElement(measure_el, "barline", location="right")
            style_name = "light-light" if b_style == "double" else "light-heavy"
            ET.SubElement(bar_el, "bar-style").text = style_name

    xml_str = minidom.parseString(ET.tostring(root)).toprexml(indent="  ") if hasattr(minidom.parseString(ET.tostring(root)), "toprexml") else minidom.parseString(ET.tostring(root)).toprettyxml(indent="  ")
    out_mxl.write_text(xml_str, encoding="utf-8")
    return out_mxl
